version: '3'
services:
  postgres:
    image: 'postgres:11.1-alpine'
    container_name: graphql-ts
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=graphql-ts
    volumes:
      - ./graphql-ts-data:/var/lib/postgresql/data

  postgres-test:
    image: 'postgres:11.1-alpine'
    container_name: graphql-ts-test
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_PASSWORD=postgres_test
      - POSTGRES_USER=postgres_test
      - POSTGRES_DB=graphql-ts-test
    volumes:
      - ./graphql-ts-test-data:/var/lib/postgresql/data
